dataset_path: lmms-lab/ai2d
task: "ai2d_mmada"
dataset_kwargs:
  token: True
test_split: test
output_type: generate_until
doc_to_visual: !function utils.ai2d_doc_to_visual
doc_to_text: !function utils.ai2d_doc_to_text
doc_to_target: !function utils.ai2d_doc_to_target
  
lmms_eval_specific_kwargs:
  default:
    prompt_format: mcq
    pre_prompt: ""
    post_prompt: ""
  gpt4v: 
    prompt_format: mcq
    pre_prompt: ""
    post_prompt: "\nAbove choices are given in {option}. {content} format.\nPlease answer with the option letter from the given choices directly."
  qwen_vl:
    prompt_format: qa
    pre_prompt: ""
    post_prompt: " Answer:"
  xcomposer2_4khd:
    prompt_format: mcq_xcomposer
    pre_prompt: "[UNUSED_TOKEN_146]user\nQuestion: "
    post_prompt: "[UNUSED_TOKEN_145]\n[UNUSED_TOKEN_146]assistant\nThe answer is"

model_specific_target_kwargs:
  default: "mcq"
  qwen_vl: "qa"

generation_kwargs:
  max_new_tokens: 16
  temperature: 0
  do_sample: False

process_results: !function utils.ai2d_reasoning_process_results

metric_list:
  - metric: ai2d_judge_acc
    aggregation: !function utils.ai2d_aggregate_judge_results
    higher_is_better: true

metadata:
  - version: 0.0