dataset_path: lmms-lab/ScienceQA
dataset_name: ScienceQA-IMG
task: "scienceqa_img_mmada"
dataset_kwargs:
  token: True
test_split: test
output_type: generate_until
doc_to_visual: !function utils.sqa_doc_to_visual
doc_to_text: !function utils.sqa_doc_to_text
doc_to_target: !function utils.sqa_doc_to_target
generation_kwargs:
  max_new_tokens: 16
  temperature: 0
  do_sample: False
metric_list:
  - metric: sqa_judge_acc
    aggregation: !function utils.sqa_aggregate_judge_results
    higher_is_better: true
process_results: !function utils.sqa_reasoning_process_results
metadata:
  - version: 0.0

lmms_eval_specific_kwargs:
  default:
    format: default
    pre_prompt: ""
    post_prompt: ""
  qwen_vl:
    format: qwen_vl
  idefics2:
    format: default
    pre_prompt: ""
    post_prompt: "\nAnswer:"
model_specific_generation_kwargs:
  llava:
    image_aspect_ratio: original
  
