dataset_name: 'arc_challenge'
output_formatter: 'default'
model_path: "/PATH/TO/llada_8b_instruct"
data_root: "/PATH/TO/DATA/ROOT/"

dataset_config:
  data_loader: 'huggingface'
  loader_fn: null
  load_dataset_args: { path: "ai2_arc", name: "ARC-Challenge" }
  split: "validation"
  doc_to_text_fn: "arc_doc_to_text"
  extract_answer_fn: "arc_extract_answer"
  is_correct_fn: "arc_is_correct"
  eval_mode: "binary"
  prompt_suffix: "<reasoning>"

generation_args:
  gen_length: 256
  block_length: 128
  temperature: 0.0

method: 'wino' #default
method_args:
  wino:
    threshold: 0.5
    threshold_back: 0.9