dataset_name: 'countdown'
model_path: "/PATH/TO/llada_8b_instruct"
data_root: "/PATH/TO/DATA/ROOT/"

dataset_config:
  data_loader: 'custom_loader'
  loader_fn: 'countdown_read_data'
  load_dataset_args: { path: "countdown/countdown_cd3_test.jsonl" }
  split: null
  doc_to_text_fn: "countdown_doc_to_text"
  extract_answer_fn: "countdown_extract_answer"
  is_correct_fn: "countdown_is_correct"
  eval_mode: "binary"
  prompt_suffix: "<reasoning>"

generation_args:
  gen_length: 256
  block_length: 128
  temperature: 0.0

method: 'wino'
method_args:
  wino:
    threshold: 0.5
    threshold_back: 0.9