dataset_name: 'math500'
output_formatter: 'default'
model_path: "/PATH/TO/llada_8b_instruct"
data_root: "/PATH/TO/DATA/ROOT/"

dataset_config:
  data_loader: 'huggingface'
  loader_fn: null
  load_dataset_args: { path: "MATH-500" }
  split: "test"
  doc_to_text_fn: "math500_doc_to_text"
  extract_answer_fn: "math500_extract_answer"
  is_correct_fn: "math500_is_equiv"
  eval_mode: "binary"
  prompt_suffix: "<reasoning>"

generation_args:
  gen_length: 256
  block_length: 128
  temperature: 0.0

method: 'wino'
method_args:
  wino:
    threshold: 0.7
    threshold_back: 0.9